language: ruby
cache: bundler
bundler_args: --without development production
rvm:
  - 2.1.5
script:
  - xvfb-run bundle exec rspec
notifications:
  email:
    recipients:
      - boss@akitaonrails.com
